package utils

import (
	"context"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// UpdateConfigMapWithRetry applies the declarative ConfigMap generated by the
// Dashboard reconciler using the resource version it observed. Despite the
// historical name, this helper deliberately does not replay the payload after
// a conflict: the Data maps may already be stale by then. Returning the
// conflict lets controller-runtime run a fresh reconciliation and regenerate
// the complete ConfigMap from current inputs.
func UpdateConfigMapWithRetry(
	ctx context.Context,
	k8sClient client.Client,
	configMap *corev1.ConfigMap,
	_ string,
) error {
	return k8sClient.Update(ctx, configMap)
}
