apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: homer-operator
    app.kubernetes.io/part-of: homer-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
