apiVersion: v2
name: homer-operator
description: A Helm chart for Homer Operator - Kubernetes operator for managing Homer dashboard instances
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/rajsinghtech/homer-operator
sources:
  - https://github.com/rajsinghtech/homer-operator
maintainers:
  - name: rajsingh
    email: raj@rajsingh.tech
keywords:
  - homer
  - operator
  - dashboard
  - kubernetes
  - service-discovery
annotations:
  category: Monitoring
  licenses: Apache-2.0