apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ExampleIngress
  annotations:
    item.homer.rajsingh.info/Name: example-ingress
    item.homer.rajsingh.info/Logo: example-ingress

spec:
  rules:
  - host: homer.rajsingh.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homer
            port:
              number: 80
  tls:
  - hosts:
    - homer.rajsingh.info
    secretName: homer-rajsingh-info-tls
